[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[[build.buildCommand]]
name = "Install system dependencies"
command = "apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-eng poppler-utils libgl1-mesa-glx libglib2.0-0"

[[build.buildCommand]]  
name = "Install Python dependencies"
command = "pip install -r requirements.txt"
